### ISSUE TITLE
[Reset password] Remove ReCaptcha from Reset password form or implement Verification code flow.

### ISSUE THREAD

**Issue by MaksVeter** [wp-digital/wp-recaptcha#1]
If you try to reset password and Google thing that you are a robot  - it's become impossible.
Probably ReCaptcha verification doesn't needed when you reset password.

**Comment by kuliebiakin** [comment]
Reset password link will be sent on user's email and verification code works in similar way, so not sure that it's reasonable to use Verification Code flow here. Also, to get verification code on login page user should type valid login/email and password but on password reset page only login/email needed which is not safe enough, I think, since attacker can identify wp-admin user's email or login.

In general it's rather done to prevent brute force, so the someone who is trying to reset password a lot of times will not able to identify users credentials (logins and emails).
